# Generated by Django 3.1.6 on 2021-02-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admin_user',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='USER_PROFILE',
        ),
    ]
