# Generated by Django 3.1.6 on 2021-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20210209_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='status',
            field=models.CharField(default='pending', max_length=16),
        ),
    ]
